name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rustup
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --verbose
    - name: Run tests
      run: cargo test --verbose
